import { Sidebar } from "@/components/dashboard/sidebar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invoice Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      lang="en"
      className={`${poppins.className} antialiased grid grid-cols-[220px_1fr] gap-x-5`}
    >
      <Sidebar />
      {children}
    </div>
  );
}
